language: node_js
dist: trusty
sudo: true
node_js:
- 8
cache:
  yarn: true
install:
- yarn add global now
- yarn install
script:
- node -r babel-register node_modules/.bin/webpack -p --config webpack.config.production.js
