version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_dev
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "8080:8080"
    networks:
      - public
networks:
  public: