export const DEPARTMENTS_LOAD_REQUEST = 'DEPARTMENTS_LOAD_REQUEST';
export const DEPARTMENTS_LOAD_SUCCESS = 'DEPARTMENTS_LOAD_SUCCESS';
export const DEPARTMENTS_LOAD_FAILURE = 'DEPARTMENTS_LOAD_FAILURE';