export const DEPARTMENTS_LOAD_REQUEST = 'DEPARTMENTS_LOAD_REQUEST';
export const DEPARTMENTS_LOAD_SUCCESS = 'DEPARTMENTS_LOAD_SUCCESS';
export const DEPARTMENTS_LOAD_FAILURE = 'DEPARTMENTS_LOAD_FAILURE';

export const EMPLOYEE_LOAD_REQUEST = 'EMPLOYEE_LOAD_REQUEST';
export const EMPLOYEE_LOAD_SUCCESS = 'EMPLOYEE_LOAD_SUCCESS';
export const EMPLOYEE_LOAD_FAILURE = 'EMPLOYEE_LOAD_FAILURE';